# Documentation: https://docs.codecov.io/docs/codecov-yaml

codecov:
  notify:
    after_n_builds: 1  # send notifications after the first upload
  bot: dlang-bot
  ci:
    # https://docs.codecov.io/docs/detecting-ci-services
    # Only CircleCi generates coverages files atm.
    # Don't wait for the other CIs
    - ci/circleci
    - !CyberShadow/DAutoTest
    - !auto-tester
    - !continuous-integration/appveyor/pr
    - !continuous-integration/jenkins/pr-merge
    - !continuous-integration/travis-ci/pr

coverage:
  precision: 3
  round: down
  range: "80...100"

  # Learn more at https://docs.codecov.io/docs/commit-status
  status:
    project:
      default:
        informational: true
        # Informational doesn't work with project yet
        threshold: 0.1
    patch:
      default:
        informational: true
    changes:
      default:
        informational: true

  # https://docs.codecov.io/docs/fixing-paths
  fixes:
    - "test/.*/::src/"
    - "fail_compilation/::src/"

comment: false
