language: d
d:
  - dmd
  - gdc
  - ldc

script: ./travis.sh

sudo: false
addons:
  apt:
    packages:
    - gdb

env:
  - MODEL=32 SELF_COMPILE=0
  - MODEL=32 SELF_COMPILE=2
  - MODEL=64 SELF_COMPILE=0
  - MODEL=64 SELF_COMPILE=2

matrix:
  include:
    - os: osx
      d: dmd-beta
      env: MODEL=32 SELF_COMPILE=0
    - os: osx
      d: dmd-beta
      env: MODEL=64 SELF_COMPILE=0
