language: d
d:
  - dmd-2.067.1
  - gdc
  - ldc

script: ./travis.sh

sudo: false
addons:
  apt:
    packages:
    - gdb

matrix:
  allow_failures:
    - d: gdc
    - d: ldc

env:
  - SELF_COMPILE=0
  - SELF_COMPILE=2
