version: 2
jobs:
  build:
    working_directory: ~/dmd
    docker:
      - image: circleci/node:4.8.2
    parallelism: 1
    branches:
      ignore:
        - dmd-1.x
    steps:
      - checkout
      - run:
          command: ./.circleci/run.sh install-deps
          name: Install DMD
      - run:
          command: sudo apt-get update && sudo apt-get install gdb
          name: Install GDB
      - run:
          command: ./.circleci/run.sh setup-repos
          name: Clone DMD & DRuntime
      - run:
          command: ./.circleci/run.sh coverage
          name: Run Phobos testsuite with -cov
      - run:
          command: ./.circleci/run.sh codecov
          name: Upload coverage files to CodeCov
